name: DragonTravel
main: eu.phiwa.dragontravel.core.DragonTravel
authors: [Phiwa, x3nec]
version: ${project.version}
load: POSTWORLD
api-version: 1.13 # We need this in order to not get legacy block Materials
softdepend: [Vault, AntiCheat, NoCheatPlus, Factions, Heroes, Towny]
permissions:
    dt.*:
        default: op
        description: All permissions
        children:
            dt.admin.*: true
    dt.admin.*:
        default: op
        description: All permissions
        children:
            dt.admin.signs: true
            dt.admin.stations: true
            dt.admin.reload: true
            dt.admin.flights: true
            dt.admin.statdragon: true
            dt.admin.remdragons: true
            dt.sethome: true
            dt.edit.*: true
            dt.travel.*: true
            dt.ctravel: true
            dt.ptravel: true
            dt.home: true
            dt.fhome: true
            dt.flight.*: true
            dt.nocost.*: true
            dt.notrequireitem.*: true
            dt.start.*: true
            dt.ptoggle: true
            dt.ignoreminheight: true
            dt.ignoredamagerestriction: true
            dt.bypassrequireskylight: true
            
    dt.admin.reload:
        description: Allow reloading of the configuration (may be buggy)

    dt.admin.signs:
        default: op
        description: Allows travels to all stations
    dt.admin.stations:
        default: op
        description: Allows travels to all stations
    dt.admin.flights:
        default: op
        description: Allows travels to all stations
    dt.admin.remdragons:
        description: Allows you to clear a world or the entire server of all dragons.
        
    dt.defaults:
        default: true
        description: Defaults available to all players
        children:
            dt.seecommand: true

    # Misc command permissions
    dt.seecommand:
        default: true
        description: See /dt in the global tab-complete (note - disallowing this will disallow all commands)

    dt.ptoggle:
        description: Allow turning off player-travels to yourself
    dt.ptoggle.other:
        description: Forcibly change the player travel toggle for another player.

    dt.sethome:
        description: Allow the player to set their home.
    
    # Station and Flight permissions
    dt.flight.*:
        description: Allows usage of every flight.
        # Use dt.flight.FLIGHTNAME for individual flights.
    dt.travel.*:
        description: Allows usage of every station.
        # Use dt.travel.STATIONNAME for individual stations.
    dt.travel.random:
        description: Allows travel to a random station.

    dt.start.*:
        children:
            dt.start.flight.*: true
            dt.start.travel.*: true
            dt.start.coord.command: true
            dt.start.player.command: true
            dt.start.home.command: true
            dt.start.fhome.command: true

    dt.start.flight.*:
        children:
            dt.start.flight.sign: true
            dt.start.flight.command: true
            dt.start.flight.command.other: true
    dt.start.travel.*:
        children:
            dt.start.travel.sign: true
            dt.start.travel.command: true

    dt.start.flight.sign:
        description: Player may start a flight from a sign
    dt.start.flight.command:
        description: Player may start a flight with a command
    dt.start.flight.command.other:
        description: Can start another player on a flight with a command

    dt.start.travel.sign:
        description: Player may start a travel to a station from a sign
    dt.start.travel.command:
        description: Player may start a travel to a station with a command

    dt.start.coord.command:
        description: Player may start a travel to coordinates with a command
    dt.start.player.command:
        description: Player may start a travel to another player with a command
    dt.start.home.command:
        description: Player may start a travel to their set home with a command
    dt.start.fhome.command:
        description: Player may start a travel to their faction's home with a command
    dt.start.tspawn.command:
        description: Player may start a travel to their town's spawn with a command


    # Permissions to edit flights and stations
    dt.edit.*:
        description: Player is allowed to edit
        children:
            dt.edit.stations: true
            dt.edit.flights: true
            dt.edit.signs: true
    dt.edit.stations:
        description: Player is allowed to edit stations
    dt.edit.flights:
        description: Player is allowed to edit flights
    dt.edit.signs:
        description: Player is allowed to edit and create signs that start a flight or travel

        
    dt.nocost.*:
        default: op
        description: Player does not need to pay for anything
        children:
            dt.nocost.travel.*: true
            dt.nocost.flight.*: true
            dt.nocost.randomtravel.*: true
            dt.nocost.ptravel: true
            dt.nocost.ctravel: true
            dt.nocost.fhome: true                  
            
    dt.nocost.travel:
        description: Player does not need to pay for anything related to travels
    dt.nocost.flight:
        description: Player does not need to pay for anything related to flights
    dt.nocost.randomtravel:
        description: Player does not need to pay for anything related to travels to random destinations
    dt.nocost.ptravel:
        description: Player does not need to pay to travel to another player
    dt.nocost.ctravel:
        description: Player does not need to pay for travels to coordinations
    dt.nocost.fhome:
        description: Player does not need to pay for travels to the faction-home
    dt.nocost.home:
        description: Player does not need to pay to travel to their set home
    dt.nocost.home.set:
        description: Player does not need to pay to set their home
    dt.nocost.home.*:
        children:
            dt.nocost.home: true
            dt.nocost.home.set: true
      
    dt.notrequireitem.*: 
        default: op
        description: Player does not need an item in any situation
        children:
            dt.notrequireitem.travel: true
            dt.notrequireitem.flight: true
    dt.notrequireitem.travel: 
        default: op
        description: Player does not need an item for travel 
    dt.notrequireitem.flight: 
        default: op
        description: Player does not need an item for flight 
        
    dt.ignoreusestations.*:
        default: op
        description: Player does not need to be at a station to start a travel or flight when station-spawnlimit is enabled
        children:
            dt.ignoreusestations.travels: true
            dt.ignoreusestations.flights: true
    dt.ignoreusestations.travels:
        default: op
        description: Player does not need to be at a station to start a travel when station-spawnlimit is enabled
    dt.ignoreusestations.flights:
        default: op
        description: Player does not need to be at a station to start a flight when station-spawnlimit is enabled  
        
    dt.ignoredragonlimit:
        default: op
        description: Allows player to mount a dragon, even if the server has already reached the limit of dragons set in the config
    dt.ignoreminheight:
        default: op
        description: Allows player to mount a dragon, even if the he is below the minimum height required to mount a dragon
    dt.ignoredamagerestriction:
        default: op
        description: Allows player to mount a dragon, even if the he received damage within the last X seconds (set via config)
    dt.bypassrequireskylight:
        default: op
        description: Allows player to mount a dragon when not in skylight

    # Legacy conversions
    dt.admin.*:
        children:
            dt.admin: true
    dt.admin.signs:
        children:
            dt.edit.signs: true
    dt.admin.stations:
        children:
            dt.travel.*: true
    dt.admin.flights:
        children:
            dt.flight.*: true
    dt.ctravel:
        children:
            dt.start.coord.command: true
    dt.ptravel:
        children:
            dt.start.player.command: true
    dt.home:
        children:
            dt.start.home.command: true
    dt.fhome:
        children:
            dt.start.fhome.command: true
    dt.tspawn:
        children:
            dt.start.tspawn.command: true
#commands:
#    dt:
#        permission: dt.seecommand